### ISSUE TITLE
Project Outline: Technologies You'll Have to Learn

### ISSUE THREAD

**Issue by coney-s** [aspiezebra/liftoff-assignments#3]
Amy, here you need to list the specific technology or technologies you will be learning to do this project. Again, refer to the group project Trello board.

**Comment by aspiezebra** [comment]
I updated it

**Comment by aspiezebra** [comment]
> Amy, here you need to list the specific technology or technologies you will be learning to do this project. Again, refer to the group project Trello board.

I updated it
